Develop
gityanizamovramil/java-explore-with-me pull request #2
Opened 2023-01-05 22:36 UTC by gityanizamovramil

2023-01-07 11:50 UTC, EugeneLenkevich requested changes
Привет, Рамиль, спасибо за PR

Первым делом поздравляю тебя с тем, что ты дошел до дипломной работы, ты крут без вариантов :)

Далее, 
наша цель в том, чтобы сделать красоту в этом проекте, все таки диплом, вдруг по нему будут оценивать навыки. Я оставил кучку коментариев, будут вопросы, задавай, не стесняйся, немножко допилить осталось :)

В целом, если честно, особо не к чему придраться, все очень солидно, но есть несколько моментов по производительности, которые хотелось бы улучшить ну и почистить немного :) 

Удачи!

2023-01-07 11:50 UTC, EugeneLenkevich commented on ewm-core/ewm-core-api/src/main/java/ru/practicum/ewm/event/dto/AdminUpdateEventRequest.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = Pattern.LOCAL_DATE_TIME_FORMAT)
Давай попробуем настроить фоматы даты и времени глобально, чтобы не приходилось вот так везде аннотациями это указывать :)

https://www.baeldung.com/spring-boot-formatting-json-dates

2023-01-07 11:50 UTC, EugeneLenkevich commented on ewm-core/ewm-core-business/src/main/java/ru/practicum/ewm/category/service/impl/CategoryServiceImpl.java
> +        findById(catId);
Не очень очевидно что тут происходит. Лучше назвать метод как то вроде exists(id)

А вот в репозитории ты можешь создать соотвествующий метод или просто наследоваться от CrudRepository, там он уже есть
Вообще exists-запрос выполняется гораздо быстрее чем полноценный  select, мелочь, но все же :)


![image](https://user-images.githubusercontent.com/109306643/211147664-1b28fadf-31fa-4a2d-8dd0-c6bb07fe6ac0.png)

2023-01-07 11:50 UTC, EugeneLenkevich commented on ewm-core/ewm-core-business/src/main/java/ru/practicum/ewm/category/service/impl/CategoryServiceImpl.java
> +        List<Category> sameNameCategories = categoryRepository.findAllByNameIgnoreCase(name);
Опять таки, лучше обойтись вот таким методом  в репозитории 
existsByName(name)
или
countByName(name)

вытаскивать пачку сущностей чтобы проверить существование объекта так себе идея - по крайней мере лишние запросы, все это помаленьку, но грузит нашу БД :) 

https://stackoverflow.com/questions/30392129/spring-data-jpa-and-exists-query

2023-01-07 11:50 UTC, EugeneLenkevich commented on ewm-core/ewm-core-business/src/main/java/ru/practicum/ewm/compilation/service/impl/CompilationService.java
> +    @Transactional
В этом же методе не происходит сохрание данных, тут не нужна транзакция, она нужна там где данные меняются - добавляются удаляются или изменяются. Тут же просто получение данных :)

2023-01-07 11:50 UTC, EugeneLenkevich commented on ewm-core/ewm-core-business/src/main/java/ru/practicum/ewm/compilation/service/impl/CompilationService.java
> +        return participationRequestRepository.countByEvent_IdAndStatus(eventId, requestStatus);
Получается что для кадой записи будети выполнен отдельный запрос в БД для подсчета количества. Это не особо оптимально, плюс, в случае если в коллекции будет много элементов, это может заметно просадить в итоге производительность :)
Получится ли сделать это все за один запрос?
Примерно такой
select count (eventId), eventId from ParticipationRequest where status=... group by eventId

2023-01-07 11:50 UTC, EugeneLenkevich commented on ewm-core/ewm-core-business/src/main/java/ru/practicum/ewm/event/mapper/EventMapper.java
> +        if (request.getAnnotation() != null) event.setAnnotation(request.getAnnotation());
Можно кстати переписать примерно так, если нравится можешь использовать :)
Optional.ofNullable(request.getAnnotation()).ifPresent(event::setAnnotation);

2023-01-07 11:50 UTC, EugeneLenkevich commented on ewm-core/ewm-core-business/src/main/java/ru/practicum/ewm/stats/service/impl/StatisticsServiceImpl.java
> +    /*@Autowired
Давай это почикаем, для истории у нас есть git :)

2023-01-07 11:50 UTC, EugeneLenkevich commented on ewm-core/ewm-core-business/src/main/java/ru/practicum/ewm/user/service/impl/UserService.java
> +        Optional<User> sameEmailUser = userRepository.findUserByEmailIgnoreCase(email);
Опять таки 
exists
и даже без Optional можно обойтись, лишний мелкий объект (плюс стати ненужная в данном случае сущность), который в итоге будет собран сборщиком мусора, то есть потратит несколько тактов процессора на свое удаление. Как бы мелочь, но, в случае высоких нагрузок и большого количества пользователей, это все влияет на производительность системы, лучше все же сразу писать пооптимальней, плюс с spring data это совсем не сложно  
Причем, это не будет преждевременной оптимизацией так как семантика записи останется та же или даже проще :)

2023-01-07 11:50 UTC, EugeneLenkevich commented on ewm-statistics/ewm-statistics-api/src/main/java/ru/practicum/ewm/stats/client/StatsClient.java
> +            /*String serverUrl, String API_PREFIX*/
Давай почикаем закомметированный код, он только засоряет :)

2023-01-07 22:44 UTC, gityanizamovramil commented on ewm-core/ewm-core-api/src/main/java/ru/practicum/ewm/event/dto/AdminUpdateEventRequest.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = Pattern.LOCAL_DATE_TIME_FORMAT)
Для объектов сделал через Configuration класс, с использованием Bean для Jackson2ObjectMapperBuilderCustomizer . Также добавил для параметров запроса вариант с имплементацией интерфейса WebMvcConfigurer для метода 
void addFormatters(FormatterRegistry registry) .

2023-01-07 22:44 UTC, gityanizamovramil commented on ewm-core/ewm-core-business/src/main/java/ru/practicum/ewm/category/service/impl/CategoryServiceImpl.java
> +        findById(catId);
Да, хорошо, что ты это заметил. Поправил здесь и в других классах.

2023-01-07 22:49 UTC, gityanizamovramil commented on ewm-core/ewm-core-business/src/main/java/ru/practicum/ewm/category/service/impl/CategoryServiceImpl.java
> +        List<Category> sameNameCategories = categoryRepository.findAllByNameIgnoreCase(name);
Поправил здесь и в других классах.

2023-01-07 22:51 UTC, gityanizamovramil commented on ewm-core/ewm-core-business/src/main/java/ru/practicum/ewm/compilation/service/impl/CompilationService.java
> +    @Transactional
Сделал правки для методов, в зависимости от того какой вид запроса (GET, PUT, PATCH и т.п.)

2023-01-07 22:54 UTC, gityanizamovramil commented on ewm-core/ewm-core-business/src/main/java/ru/practicum/ewm/compilation/service/impl/CompilationService.java
> +        return participationRequestRepository.countByEvent_IdAndStatus(eventId, requestStatus);
Исправил. В результате часть кода стала оптимизировалась.

2023-01-07 22:56 UTC, gityanizamovramil commented on ewm-core/ewm-core-business/src/main/java/ru/practicum/ewm/event/mapper/EventMapper.java
> +        if (request.getAnnotation() != null) event.setAnnotation(request.getAnnotation());
Да, поправил. 

Я правильно понимаю, что Optional.ofNullable() не будет создавать дополнительные объекты ?

2023-01-07 22:56 UTC, gityanizamovramil commented on ewm-core/ewm-core-business/src/main/java/ru/practicum/ewm/stats/service/impl/StatisticsServiceImpl.java
> +    /*@Autowired
Убрал лишнее.

2023-01-07 22:56 UTC, gityanizamovramil commented on ewm-core/ewm-core-business/src/main/java/ru/practicum/ewm/user/service/impl/UserService.java
> +        Optional<User> sameEmailUser = userRepository.findUserByEmailIgnoreCase(email);
Круто, так намного лучше. Спасибо.

2023-01-07 22:57 UTC, gityanizamovramil commented on ewm-statistics/ewm-statistics-api/src/main/java/ru/practicum/ewm/stats/client/StatsClient.java
> +            /*String serverUrl, String API_PREFIX*/
Здесь тоже почистил.

2023-01-08 03:57 UTC, EugeneLenkevich commented on ewm-core/ewm-core-api/src/main/java/ru/practicum/ewm/event/dto/AdminUpdateEventRequest.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = Pattern.LOCAL_DATE_TIME_FORMAT)
Обычно делается настрйока глобально, чтобы все работало единообразно и потом не держать в голове такие детали. Для конкретного класса можно конечно и свои форматы указать, но это какой то частный случай, например, интеграция с какой то внешней системой в которой свой формат даты. Тогда именно для взаимодействия с ней мы делаем выделенный dto со специфическими настройками. Как то так :)

2023-01-08 04:00 UTC, EugeneLenkevich commented on ewm-core/ewm-core-business/src/main/java/ru/practicum/ewm/compilation/service/impl/CompilationService.java
> +    @Transactional
Нене, от типа http-запроса это никак не зависит. Транзакции - это уровень сервиса, в общем случае сервис ничего не знает откуда его вызывают, это же может быть и другой сервис и задача, выполняющаяся по расписанию, то есть там вообще может не быть http.
В общм надо смотреть внутри метода, ести ли там insert, update или delete

2023-01-08 04:04 UTC, EugeneLenkevich commented on ewm-core/ewm-core-business/src/main/java/ru/practicum/ewm/event/mapper/EventMapper.java
> +        if (request.getAnnotation() != null) event.setAnnotation(request.getAnnotation());
Будет, скрин ниже.

Вообще тут смысл такой. Мы всегда ищем баланс между читаемостью кода и производительностью. В общем случае следует выбирать читаемость кода и не упарываться в преждевременную оптимизацию. Но если можно записать код более оптимально без нарушения семантики, то стоит писать более оптимально. Тут все зависит от нашего чувства прекрасного :)

![image](https://user-images.githubusercontent.com/109306643/211179927-feab7da2-526a-45e6-823d-98079f297a35.png)

2023-01-08 04:11 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-01-08 04:11 UTC, EugeneLenkevich commented on ewm-core/ewm-core-business/src/main/java/ru/practicum/ewm/compilation/service/impl/CompilationService.java
> +            eventMap.get(c.getEventId()).setConfirmedRequests(c.getParticipationCount());
Во, супер, с мапой отличное решение)

2023-01-08 13:18 UTC, merged